os:
  - linux
  - osx
dist: bionic
osx_image: xcode10.3
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - libphysfs-dev
      - libsdl2-dev
  homebrew:
    packages:
      - boost
      - physfs
      - sdl2
script:
  - cmake .
  - make
